eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      mvc:
        ## Product Service Route
        routes[0]:
          id: product-service
          uri: lb://product-service
          predicates[0]: Path=/api/product

        ## ORDER Service Route
        routes[1]:
          id: order-service
          uri: lb://order-service
          predicates[0]: Path=/api/order

        ## DISCOVERY SERVER Route
        routes[2]:
          id: discovery-server
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/web
          #DEFINING A FILTER TO REROUTE URL PATH
          filters[0]: SetPath=/
        ## DISCOVERY SERVER STATIC Route
        routes[3]:
          id: discovery-server-static
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/**
          #DEFINING A FILTER TO REROUTE URL PATH



logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionsLocator: INFO



