
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Order
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: order
    hibernate:
      ddl-auto: create
    show-sql: true

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1.0

      #KAFKA PROPERTIES
  kafka:
    bootstrap-servers: localhost:9092
    template:
        default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.leron.orderservice.event.OrderPlacedEvent


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka


management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



#Resilience 4J properties
resilience4j:
  circuit-breaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

        #Resilience 4J Timeout properties
  time-limiter:
    instances:
      inventory:
        timeout-duration: 3s

     #Resilience 4j Retry properties

  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s







