spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Order
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: order
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    integration:
        enabled: true
    sampler:
        probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8083
